import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ppEditorialNew = localFont({
  src: "../public/PPEditorialNew-Ultralight.otf",
  variable: "--font-pp-editorial-new",
  display: "swap",
});

const interDisplay = localFont({
  src: "../public/InterDisplay-Medium.woff2",
  variable: "--font-inter-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ppEditorialNew.variable} ${interDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
